### ISSUE TITLE
After disagreeing the terms and pressing back tinker loads infinitely. 

### ISSUE THREAD

**Issue by Quantoxis** [Moros1138/PGEtinker#112]
If you disagree to the terms then press back it doesn't present the terms again. Tinker just loads infinitely on the homepage.
I got this by going to the website, pressing disagree, I reached the you've disagreed page and then pressed back on my browser. Happens in both Firefox on desktop in Windows and Safari on iOS.

You can get it back by pressing the logo.
![image](https://github.com/Moros1138/PGEtinker/assets/5701124/59d05289-5625-40cf-b96d-810ed9fdad27)

**Comment by Moros1138** [comment]
thought i fixed it, works on my local test environment before building the final static files, but once built, the behavior reverts. investigating.

**Comment by Moros1138** [comment]
nailed it in latest #115
