### ISSUE TITLE
Progress Steps

### ISSUE THREAD

**Issue by mrutkowsk** [Moros1138/PGEtinker#116]
## Reason
The hall idea of this webpage : developed programming skills. 

## IDEA

###description
 "Step Tabs". As easy as possible, but to be able to switch between them to compile and see the result.

If tutorial is developed, to be able to save separately stages, similar to GitHub, but in our case, just simple text : Step 1, Step 2, Step 3, etc
It is   (copy, paste is slow and inconvenient :) )

# Last
Using opportunity to say Thank You, this is awesome :)

**Comment by Moros1138** [comment]
You're welcome! Thanks for your feedback.

This does sound like a fun idea. I have to think about how I would go about implementing a feature like this without requiring the ability to track users and store data.

I could rant about data privacy for hours but the north star with PGEtinker is relatively simple. "I can't sell data I don't collect", I collect as little data as possible to operate. If I don't absolutely need to collect it, I don't.

**Comment by Moros1138** [comment]
Accidentally closed the issue, reopened

**Comment by mrutkowsk** [comment]
What about to not store info of Your guests, only create vote system for examples itself → separate list for examples where visitors from Your group (trusted visitors) have right to vote for examples, and after time "B" examples without vote will be deleted.
My argument for this : only people with "proven experience" can decide is example is valuable enough to stay on Your website permanently. OLC team should start asking "apply" to get "membership" (reference necessary) or 1-year history (example) of portfolio on GitHub (something to reduce fakes) ...
 ....I understand this is a lot but if something can be abused, will be abused, and this is my idea to limit it. Applicant Accountability is a key, and they have to have something to lose. Random guests statistically will create chaos, unfortunately, and democracy is also not enough because majority often is wrong. Proven experience is the only factor to guaranty quality.
I do not have 1y of history on GitHub, so I won't be able to vote on examples, but I start working on it :)

Again .. Impressive work :) Regards

PS.

1.b - visitor have a simple check box (default off)    - save as Public example (if approved)    (owner receive long hash, if lost ownership is lost),  ...(this creates few questions how to edit potential mistakes, but I stop this point now :)  ) 
1 - Example have hash, and "separate" group is deciding is this example will stay on the list.  
2 - with time would be useful to add tags / classification to examples, also decided by the group
3 -"Thank You list" to display  name / alias  of top contributes (if they agree)   as top 100, but in random order  . Each time list is displaying top 100 contributors in random order 

I stop now to not waste  more of Your time. I will only respond if  You include ABC in Your "potential" response :)  

Regards

English is my 2 language, and I do not use GPT to fix it, :) apologise for mistakes.
