### ISSUE TITLE
Bug in Version: 92bea0d. Non existant header error indication

### ISSUE THREAD

**Issue by Piratux** [Moros1138/PGEtinker#57]
**Describe the bug**
Adding non existent header include shows no error indication, and is stuck on "Compiling".
Example of non existent header:
```c
#include "olcPixelGameEngine_.h"
```

**To Reproduce**
1. Add `#include "olcPixelGameEngine_.h"` at the top of source code
2. Click Build & Run.

**Expected behavior**
Some kind of error indication.

![image](https://github.com/Moros1138/PGEtinker/assets/58703216/ac5f3875-6b51-4ead-a524-11840d3a8692)

**Desktop (please complete the following information):**
 - Firefox

**Comment by Moros1138** [comment]
This bug has been fixed, but not released on the bixxy deployment, but thanks for the report!
