### ISSUE TITLE
Scrolling back up in the console while data continues to be written to stdout

### ISSUE THREAD

**Issue by sigonasr2** [Moros1138/PGEtinker#70]
**Is your feature request related to a problem? Please describe.**
As I work on applications in PGEtinker, occasionally I want to output data to the console repeatedly to monitor values. If I don't include a way to stop monitoring values, I have no way to scroll back up while my program continues to add info to the Console.

**Describe the solution you'd like**
When I start scrolling back up in the `Console` window, the window won't immediately put the scrollbar focus back to the bottom of the panel (since it's still being updated and written to constantly)

**Describe alternatives you've considered**
As I mentioned before, it's currently on the user to implement a way to stop producing debugging outputs everytime they want to test per-frame debugging, but gets quite annoying after constant use of it.

**Additional context**
For an example, see: https://beta.pgetinker.com/s/TUGKC3iS9N1

As it outputs an incrementing counter number, I cannot scroll the Console window back up to look at previous values.

(As a side note, when the scrollbar is already at the bottom, the window can continue scrolling on its own. There are just some instances where interrogating a specific value while the console continues outputting would be handy.)

**Comment by Moros1138** [comment]
Thanks for the perfect example to use to test with! I'll fix this.
