### ISSUE TITLE
Bug in Version: 23c0cb0

### ISSUE THREAD

**Issue by sigonasr2** [Moros1138/PGEtinker#73]
**Describe the bug**
When attempting to use Draw functions with `olcUTIL_Geometry2D.h` included, programs no longer compile.

**To Reproduce**
1. Start with a default code template in PGEtinker.
2. Add the line: `#include "olcUTIL_Geometry2D.h"` before `#include "olcPixelGameEngine.h"`
3. Click the "Build & Run" button.
4. Observe that linker errors appear for any draw functions that are using the olc vector types:
> ```
> wasm-ld: error: pgetinker.o: undefined symbol: olc::PixelGameEngine::FillCircle(olc::v_2d const&, int, olc::Pixel)
> wasm-ld: error: pgetinker.o: undefined symbol: olc::PixelGameEngine::Draw(olc::v_2d const&, olc::Pixel)
> ```

**Expected behavior**
The program would run and compile as normal, showing the standard PGEtinker application.

 - OS: Windows 11
 - Browser: Microsoft Edge (Tested on Google Chrome as well)

**Comment by Moros1138** [comment]
Ahhh, this is a sneaky little bug. I did a little investigating and I know how to fix it, should be up along with the next screenshot/thumbnail release..
