### ISSUE TITLE
#define OLC_PGE_APPLICATION line can have miscellaneous text surrounding it (No Side Effects) - Bug in Version: aee3eb2

### ISSUE THREAD

**Issue by sigonasr2** [Moros1138/PGEtinker#78]
**Describe the bug**
Typing anything before or after `#define OLC_PGE_APPLICATION` is considered legal, but does not appear to have any other consequences.

**To Reproduce**
1. Start PGEtinker with the default code.
2. On the top line with `#define OLC_PGE_APPLICATION`, write any text of your desires either before or after it.
3. Click Run and see that it builds fine with no side effects.

**Expected behavior**
Probably should error with an invalid name/type/symbol error of some sort from the compiler? 

**Additional context**
Here is an example PGEtinker share demonstrating the "problem": https://beta.pgetinker.com/s/L-YwkrmuLLV

**Comment by Moros1138** [comment]
First. Thank you for almost always giving me a direct example I can use to test.. It really helps me to quickly identify the issue.

Second. I know why this happens.

https://github.com/Moros1138/PGEtinker/blob/main/pgetinker/Compiler.php#L180

I'll refine this check to do it in a less naive way. Thanks again.

**Comment by Moros1138** [comment]
This fix has been deployed!
